### PR TITLE
Merged across all the patches to `d3-zoom` incrementally

### LINKED ISSUE #3: Using d3-xyzoom click events are swallowed
If you use `d3-xyzoom` in the usual way then it swallows click events, unlike `d3-zoom`. Here's a codepen illustrating the effect: https://codepen.io/IPWright83/pen/RLgKer?editors=1011

Copy of the code I'm using to reproduce this issue. Clicking on the circle won't trigger the clicked event:

```
const zoom = d3
  .xyzoom()
  .extent([[0, 0], [250, 250]])
  .scaleExtent([0.5, 10])
  .on("zoom", () => {
    d3.select(target)
      .select("g")
      .attr("transform", d3.event.transform);
  });

  d3.select(target).call(zoom);

  d3.select(target)
    .select("circle")
    .on("click", () => {
    alert("clicked d3-xyzoom");
  });
```

### PR DESCRIPTION
**Pull request by IPWright83**
In theory this should fix https://github.com/etiennecrb/d3-xyzoom/issues/3

### CODE REVIEW

**Review by etiennecrb — APPROVED** [review]
Thank you!

**Comment by IPWright83** [comment]
@etiennecrb would you be able to publish this latest version to `npm`?

**Comment by etiennecrb** [comment]
Sorry, I forgot! It's done.

**Comment by IPWright83** [comment]
@etiennecrb thank you!

**Pull request merged**
